# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "rudi.prihandoko.id" # the base hostname & protocol for your site
# excerpt_separator: <!--more-->

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Midnight Notes
  avatar: ava500.png # Taken from Freepik http://www.freepik.com/free-vector/avatars-in-cartoon-style_766799.htm
  gravatar: # Email MD5 hash
  description: "Notes to Myself" # used by search engines

  # Header and footer text
  header_text: >
     <p>You can never edit a piece of blank paper.</p>
     <p>--Anonym</p>

  header_text_feature_image: https://source.unsplash.com/category/nature/1600x1200
  footer_text: >
   Powered by <a href="http://github.com">Github</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: true
  email_address: rudi@prihandoko.id # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: ruuds
  flickr: rudi-prihandoko
  github: rud72k
  google_plus: +RudiPrihandoko
  instagram: prihandokorudi
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam: rudipekok
  tumblr:
  twitter: "prihandokorudi"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-75027306-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: midnightnotestomyself
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rogue
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]